### PR TITLE
User can query a singular tag for events

### PR DESCRIPTION
**Pull request by jhuang09**
User can enter a link like `/event-list?tags=food` and the page will display a JSON that contains all the events that have "food" as its substring.

(Some issues that may arise is if a string contains "food" -- something like "dwaojnlnfoodkdlwa" -- the event will still be displayed in the JSON.)

### CODE REVIEW

**Comment by jhuang09** [comment]
I'm currently working on how to get the messages to display, not just the JSON! (I'm very close to getting it :))

**Comment by mrios730** [comment]
Hi Janny, sorry for checking on this so late, but how would the url be formatted to check for a tag such as "food"?

**Comment by jhuang09** [comment]
Heya! It would be something like `http://localhost:8080/event-list.html?tags=food`.

**Comment by mrios730** [comment]
Cool!

**Review by mrios730 — APPROVED** [review]

**Pull request merged**
