### PR TITLE
Added Material Design Lite compoents to User and Stats pages

### PR DESCRIPTION
**Pull request by dhgarrette**

### CODE REVIEW

**Comment by mrios730** [comment]
HI Dan, which button is suppose to change in color? I didn't notice a change when I ran it.

**Comment by dhgarrette** [comment]
MDL has a notion of a base color and an accent color, which are given in the CSS import `https://code.getmdl.io/1.3.0/material.indigo-orange.min.css`.  So if you look at the User page, most of the elements should be indigo colored, and a few things will be orange, including the "Submit" and "Send" buttons.

**Comment by mrios730** [comment]
For some reason, it's not working for me.
Screen Shot 2019-04-07 at 11 52 20 AM

**Comment by mrios730** [comment]
I realized that I did not properly switch branches. Sorry about that. The page looks good!

**Review by mrios730 — APPROVED** [review]

**Comment by dhgarrette** [comment]
Oh, ha, cool.  Ok, I've merged it.  :-)

**Pull request merged**
