### PR TITLE
Updated MessageServlet to be able to display images when given a link

### PR DESCRIPTION
**Pull request by jhuang09**

### CODE REVIEW

**Comment by jhuang09** [comment]
It's not entirely foolproof just yet, but I plan on working on it later tonight. I can make another PR :)

**Review by dhgarrette — COMMENTED** [review]
Cool! Thanks, Janny!  I have one thought though: converting part of the user's message into html seems like something that only has to do with displaying the message, so I'm thinking that instead of adding html to the message before we store it, we should add the html as we display it.  So maybe you can move the code you added up to the `doGet` method.  How about this:

* Create a function called something like `prepareMessageForDisplay(Message message)` in `MessageServlet`.
* Move your regex replacement code into `prepareMessageForDisplay`, so that you replace `message`'s text (using `getText` and `setText`).
* Then, in `doGet`, loop through `messages`, passing each message to `prepareMessageForDisplay`.

Does that make sense?

**Comment by jhuang09** [comment]
That makes sense! I've updated the files. I wasn't too sure if line 49 in `MessageServlet.java` is a necessary step or if I should just combine it with line 50. Any thoughts about combining it or leaving it as is?

**Review by dhgarrette — APPROVED** [review]
Looks great!  Thanks for making that change, Janny!  We'll also be able to reuse that method going forward for other custom message displaying behavior.

**Pull request merged**
