### PR TITLE
Added a MessageTransformer for Image Url handling

### PR DESCRIPTION
**Pull request by jhuang09**
Migrated contents handling images to its own MessageTransformer class. Will add test cases to double check that the migration has not changed its functionality.

### CODE REVIEW

**Comment by jhuang09** [comment]
(Small note: I've got class in a bit, but will take a look at the errors in 2.5 hours!)

**Comment by jhuang09** [comment]
I'm actually not sure what's going on with the Travis CI and what the errors mean. Thoughts?

Edit: I realized I didn't actually add the new file I created!

**Comment by mojuwara** [comment]
I just want to make sure I understand everything.

Why did you comment out the code in the **testPrepareMessageForDisplay()** method in the **MessageServletTest** file?

And is it supposed to let me upload images yet? When I go to http://localhost:8080/messages, I get the empty array ([]) when I'm "logged in" as test@example.com.

**Comment by jhuang09** [comment]
I commented out the tests in `MessageServletTest` because when I originally moved the image url handling portion of the `prepareMessageForDisplay` method in `MessageServlet`, the tests were failing since it was calling the method from `MessageServlet`. However, I think I might move the tests in the `MessageServletTest` file to another test file called `ImageUrlMessageTransformerTest` file. I'm not sure if that makes sense, but my plan was to transfer some contents of `MessageServletTest` to `ImageUrlMessageTransformerTest` later, but I comment out the code in `MessageServletTest` just so that I could run `mvn appengine:devserver` without the failing tests getting in the way.

As for uploading images, I don't think the entire uploading portion has been implemented yet! I've only gotten it to process the uploading of a local file, but Datastore doesn't actually store any of the information yet. I believe converting a valid URL to an image should still be working, though!

I'm also getting the same issue with an empty array with just `/messages` or when it's  when I have something like:
http://localhost:8080/messages?recipient=test@example.com
When the link is:
http://localhost:8080/messages?user=test@example.com,
then the messages appear as a JSON (I think?). I think `/messages` needs to specify a user so that it knows whose messages to retrieve, but I'm not entirely sure if that's the right idea. What do you think?

**Comment by mojuwara** [comment]
I see. It sounds like a good idea to move the tests for Image URL's to a different file and have them test the ImageUrlMessageTransformer.

Okay. I uploaded a link (https://en.wikipedia.org/wiki/Portable_Network_Graphics#/media/File:PNG_transparency_demonstration_1.png) and it worked! I can see the JSON element when the url is http://localhost:8080/messages?user=test@example.com.

I think you should be able to see any messages where you are either the recipient or the sender. 

Maybe we can use the code on **lines 40-43** of **LoginServlet.java** to check if someone is logged in. It also has a way to get their email address which we could use as the user parameter in the **getMessagesByRecipient(user)** method. What do you think?

**Comment by jhuang09** [comment]
That makes sense! I have just moved all the tests to the `ImageUrlMessageTransformerTest.java` file. 

I'll get to working on the portion pertaining to the message retrieval now :)

**Comment by mojuwara** [comment]
This looks really good!

**Review by dhgarrette — APPROVED** [review]

**Comment by dhgarrette** [comment]
Resolves Issue #45

**Comment by jhuang09** [comment]
Note: I'll work on the message retrieval portions in another PR!

**Pull request merged**
