### PR TITLE
Added storeEvent method to Datastore class

### PR DESCRIPTION
**Pull request by jhuang09**

### CODE REVIEW

**Comment by mojuwara** [comment]
Looks good. I think we should also store the description for the event.

**Review by mojuwara — CHANGES_REQUESTED** [review]
I think we should store the description for the event as well.

**Comment by jhuang09** [comment]
Good call, Mo! I've updated the `Datastore.java` file. Let me know what you think!

**Review by mojuwara — APPROVED** [review]

**Comment by mojuwara** [comment]
Nice!

**Comment by jhuang09** [comment]
Thanks! :)

**Comment by dhgarrette** [comment]
Fixes the first half of Issue #48.

**Pull request merged**
