### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by mrios730**
Not sure why I'm getting stickler-ci errors

### CODE REVIEW

**Review by jhuang09 — DISMISSED** [review]
Looks pretty good! I would change the font color for the messages too so that it is easier to read, and also link the CSS files to the `starbucks-map.html` and `map.html` pages. Otherwise, looks great! :)

**Review by jhuang09 — COMMENTED** [review]
Looks pretty good! I would change the font color for the messages too so that it is easier to read, and also link the CSS files to the starbucks-map.html and map.html pages. Otherwise, looks great! :)

**Comment by mrios730** [comment]
Hey Janny! Instead of changing the font color, I just made the background of the messages white and kept the text black. I also changed the background color of the website because I like light blue better :)

**Review by jhuang09 — APPROVED** [review]
Awesome! Looks great :)

**Pull request merged**
